# Generated by Django 4.2.6 on 2025-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
